name: Test build wep app image
description: Build wep app image

inputs:
  username:
    description: 'User name for docker image storage'
    required: false
    default: ${{ secrets.DOCKERHUB_USER }}
  password:
    description: 'User password for docker image storage'
    required: false
    default: ${{ secrets.DOCKERHUB_PASSWORD }}
  image_tag:
    description: 'Image tag'
    required: false
    default: latest
  dockerfile:
    description: 'Docker file patch'
    required: false
    default: docker/web/Dockerfile
  context:
    description: 'Context docker build'
    required: false
    default: .
  image_name:
    description: 'Image Name'
    required: false
    default: app

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        image_name: ${{ inputs.image_name }}
        image_tag: ${{ inputs.image_tag }}
        push_git_tag: false
        context: ${{ inputs.context }}
        dockerfile: ${{ inputs.dockerfile }}
