name: CI

on:
  push:
    branches:
      - '*'
      - '!main'
    paths:
      - '**.js'
      - '**.ts'
      - 'docker/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  quality:
    if: github.event_name != 'pull_request'
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Quality
        uses: ./.github/actions/quality
        with:
          tool_name: eslint-github-check
          reporter: github-check

  unit-tests:
    if: github.event_name != 'pull_request'
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Test
        uses: ./.github/actions/unit-tests

  functional-tests:
    if: github.event_name != 'pull_request'
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Run Functional Tests
        uses: ./.github/actions/functional-tests

  buid-image-test:
    if: github.event_name != 'pull_request'
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Build Image
        uses: ./.github/actions/buid-image
